### ISSUE TITLE
Publish and announce availability of Cloudflare speed test data

### ISSUE THREAD

**Issue by laiyi-ohlsen** [m-lab/etl-schema#151]
- [x] deploy measurement-lab.cloudflare.speedtest_speed1 @stephen-soltesz 
- [x] develop colab to demonstrate access to both ndt and aim data @laiyi-ohlsen 
- [x] create data visualization of AIM Data for announcement blog post @laiyi-ohlsen 
- [x] make measurement-lab.cloudflare.speedtest_speed1 public via discuss@ permissions @stephen-soltesz 
- [x] publish announcement @laiyi-ohlsen

**Comment by stephen-soltesz** [comment]
@laiyi-ohlsen [`measurement-lab.cloudflare.speedtest_speed1`](https://console.cloud.google.com/bigquery?project=mlab-cloudflare&ws=!1m5!1m4!4m3!1smeasurement-lab!2scloudflare!3sspeedtest_speed1) is now available, but not yet public.

**Comment by laiyi-ohlsen** [comment]
Cloudflare announcement will go live sometime week, making the data available to the public on 11/21 would be much appreciated

**Comment by stephen-soltesz** [comment]
Actually, @laiyi-ohlsen do you know how to apply the ACL to the dataset to make it accessible to the public? If not, I would like to walk through it with you so that you know how to do it too.

**Comment by laiyi-ohlsen** [comment]
^ Walking through Monday!

**Comment by laiyi-ohlsen** [comment]
[measurement-lab.cloudflare.speedtest_speed1](https://console.cloud.google.com/bigquery?project=mlab-cloudflare&ws=!1m5!1m4!4m3!1smeasurement-lab!2scloudflare!3sspeedtest_speed1) is now public!

**Comment by stephen-soltesz** [comment]
Blog post announcement: https://www.measurementlab.net/blog/cloudflare-aimscoredata-announcement/
