### ISSUE TITLE
Add ISO 3166-2 subdivision 2 code and name fields to ndt schema

### ISSUE THREAD

**Issue by critzo** [m-lab/etl-schema#18]
To accompany https://github.com/m-lab/annotation-service/issues/217 consider adding two additional client related region field to the NDT schema:

* subdivision_2_iso_code
* subdivision_2_name

These fields are present in [Maxmind Geolite2-City Locations](https://github.com/m-lab/annotation-service/blob/master/geolite2/testdata/GeoLite2City/GeoLite2-City-Locations-en.csv).

**Comment by critzo** [comment]
These fields have been added to `measurement-lab.raw_ndt.annotation` in production, along with a few others:
* client.Network.ASNumber
* client.Network.ASName
* client.Geo.Subdivision1ISOCode
* client.Geo.Subdivision1Name
* client.Geo.Subdivision2ISOCode
* client.Geo.Subdivision2Name
* client.Geo.AccuracyRadiusKm

The next update to tables and views should include all these fields.

**Comment by mattmathis** [comment]
I think this is done but not closed for some reason.
