### ISSUE TITLE
Change ASN fields to top level and integer

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl-schema#29]
The ASN fields should be integers.  If we want to capture AS Sets, that should be done in a struct field.

We also want to use bigquery clustering on some fields, to improve query performance.  We likely want to use ASN, which would mean these must be top level fields (possibly redundant with client/server fields).

**Comment by gfr10598** [comment]
Part of https://github.com/m-lab/etl/issues/643

**Comment by mattmathis** [comment]
Previously implemented.
