### ISSUE TITLE
ndt7 unified view server Geo uses client incorrectly

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl-schema#83]
The new ndt7 unified views incorrectly use the client geo for the server fields.

https://github.com/m-lab/etl-schema/blob/master/views/library/referenced-by/ndt_unified_ndt7_downloads.sql#L139-L156

This can easily be fixed by referencing the corresponding `server.` fields instead of `client.`

**Comment by stephen-soltesz** [comment]
@mattmathis

**Comment by mattmathis** [comment]
See: Update server geo from the correct fields (#84)
