### ISSUE TITLE
allow access to query views referenced by raw_ndt views

### ISSUE THREAD

**Issue by critzo** [m-lab/etl-schema#86]
Discuss group members can view the tables/views in `measurement-lab.raw_ndt`, but do not have permissions to query them since the views reference tables in `mlab-oti`:
![image](https://user-images.githubusercontent.com/4633345/94048374-69835c80-fda1-11ea-8bed-19bb714cc7a0.png)
![image](https://user-images.githubusercontent.com/4633345/94048408-799b3c00-fda1-11ea-98fb-6f145af250d1.png)

**Comment by critzo** [comment]
@gfr10598 is it possible to apply this permission this week? We have some partners that wish to obtain AS Name, and this issue is a blocker. Seems like an ACL hasn't been applied or something.

**Comment by stephen-soltesz** [comment]
@critzo can you confirm this is WAI now? I've manually added the measurement-lab.raw_ndt views as "authorized views" to the mlab-oti.raw_ndt dataset. This was my mistake originally.

**Comment by critzo** [comment]
@stephen-soltesz Confirmed, WAI. Thank you!
